{{- if .Values.kiac.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kiac.serviceAccountName" . }}
  labels:
    {{- include "kiac.labels" . | nindent 4 }}
  {{- with .Values.kiac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kiac.labels" . | nindent 4 }}
  name: {{ include "kiac.fullname" . }}
rules:
# TODO remove extensions based on the --ingress-api-version flag
- apiGroups:
  - extensions
  - networking.k8s.io
  - ""
  resources:
  - ingresses
  - pods
  verbs:
  - get
  - list
  - watch
# TODO remove extensions based on the --ingress-api-version flag
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - zalando.org
  resources:
  - routegroups
  verbs:
  - get
  - list
- apiGroups:
  - zalando.org
  resources:
  - routegroups/status
  verbs:
  - patch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kiac.fullname" . }}
  labels:
    {{- include "kiac.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kiac.fullname" . }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: {{ include "kiac.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
