{{- range $key, $val := .Values.plan }}
{{- if $val.enabled }}
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: {{ $key }}
spec:
  version: {{ $val.version }}
  serviceAccountName: {{ include "system-upgrade-controller.serviceAccountName" $ }}

  secrets:
    - name: {{ include "system-upgrade-controller.serviceAccountName" $ }}-talos
      path: /var/run/secrets/talos.dev
      ignoreUpdates: true

  exclusive: true
  concurrency: 1
  jobActiveDeadlineSecs: {{ default 3600 $val.jobActiveDeadlineSecs }}
  window:
    days: ["mo", "tu", "we", "th"]
    startTime: "10:00:00"
    endTime: "18:00:00"
    timeZone: "UTC"

  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

  upgrade:
    image: ghcr.io/siderolabs/talosctl:{{ $.Values.talosVersion }}
    envs:
      - name: NODE_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    args:
      - --nodes=$(NODE_IP)
      - upgrade-k8s
      - --to=$(SYSTEM_UPGRADE_PLAN_LATEST_VERSION)
      - --with-docs=false
      - --with-examples=false

    securityContext:
      {{- toYaml $.Values.securityContext | nindent 6 }}
{{- end }}
{{- end }}
