# Default values for openvpn.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/sergelogvinov/openvpn
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

certManager:
  # -- Create certificates using cert-manager.
  createCerts: false

  # -- Common name for the certificate.
  commonName: ~
  # -- Subject for the certificate.
  subject:
    {}
    # countries:
    #   - US
    # organizations:
    #   - Let's Encrypt

  # -- If clientConfigRBAC = true, clients list is kubernetes username.
  clientConfigRBAC: false
  # -- List of clients.
  clients:
    []
    # - user1@dmain.com
    # - user2

# -- Kubernetes cluster domain.
clusterDomain: ~

dns:
  # -- Create a DNS server in the pod.
  enabled: false

openvpn:
  # -- Server domain name.
  hostName: vpn.example.com

  # -- OpenVPN configuration file.
  config:
    ~
    # server 172.30.0.0 255.255.255.0
    # topology p2p
    # data-ciphers AES-256-GCM:AES-128-GCM
    # data-ciphers-fallback AES-256-CBC

    # push "dhcp-option DNS 172.30.0.1"

    # max-clients 60
    # # duplicate-cn
    # # client-to-client

  # -- Route all traffic through VPN.
  redirectGateway: false
  # -- Custom routes.
  defaultroutes:
    ~
    # push "route 8.8.8.8   255.255.255.255"

  # -- One-time password.
  otp:
    ~
    #
    # google-authenticator -tdfWq -r 3 -R 30
    #

  # -- Custom root certificate, if createCerts==false.
  ca:
    ~
    # -----BEGIN CERTIFICATE-----
    # -----END CERTIFICATE-----
  # -- Custom server certificate, if createCerts==false.
  cert:
    ~
    # -----BEGIN CERTIFICATE-----
    # -----END CERTIFICATE-----
  # -- Custom server private key, if createCerts==false.
  key:
    ~
    # -----BEGIN PRIVATE KEY-----
    # -----END PRIVATE KEY-----

  # -- Revoke certificates.
  revoke:
    ~
    ## openssl.cnf
    # [ ca ]
    # default_ca      = CA_default
    # [ CA_default ]
    # dir             = .
    # database        = $dir/index.txt
    # default_md      = sha256
    # default_crl_days= 1000

    # touch index.txt
    # openssl ca -cert ca.crt -keyfile ca.key -revoke client.crt -config openssl.cnf
    # openssl ca -cert ca.crt -keyfile ca.key -gencrl -out revoke.pem -config openssl.cnf
    # openssl crl -text -noout -in revoke.pem
    #

  # -- TLS version and ciphers.
  tlsversion:
    {}
    # tls-version-min: 1.2
    # tls-cipher: TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256

  # -- TLS authentication.
  # openvpn --genkey secret ta.key
  tlsauth:
    ~
    # -----BEGIN OpenVPN Static key V1-----
    # -----END OpenVPN Static key V1-----

  # -- Diffie-Hellman parameters.
  # openssl dhparam -out dh2048.pem 2048
  dh:
    ~
    # -----BEGIN DH PARAMETERS-----
    # -----END DH PARAMETERS-----

# -- Annotations for pod.
# ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}

# -- Pod Security Context.
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
podSecurityContext:
  runAsUser: 0
  runAsGroup: 101
  fsGroup: 101
  fsGroupChangePolicy: "OnRootMismatch"

# -- Container Security Context.
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
securityContext:
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    add:
      - NET_ADMIN
      - MKNOD
      - SETUID
      - SETGID
    drop:
      - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 0
  runAsGroup: 101

# -- Service parameters
# ref: https://kubernetes.io/docs/user-guide/services/
service:
  type: ClusterIP
  ipFamilies: [IPv4]

  # -- Protocol for service.
  # Can be TCP, UDP or All.
  proto: udp
  port: 1190
  # nodePort: 1190

  annotations: {}

  ports:
    []
    # - name: postgres
    #   port: 5432
    #   backend: postgres.default.svc.cluster.local:5432
    #   tls: true

# -- Resource requests and limits.
# ref: https://kubernetes.io/docs/user-guide/compute-resources/
resources:
  limits:
    cpu: 1
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 32Mi

# -- Use a daemonset instead of a deployment
useDaemonSet: false

# -- pod deployment update strategy type.
# ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#updating-a-deployment
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1

# -- Node labels for pod assignment.
# ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

# -- Tolerations for pod assignment.
# ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

# -- Affinity for pod assignment.
# ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}
