# Default values for victoria-metrics.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

vmstorage:
  replicaCount: 1
  autoscaling:
    enabled: false

  extraArgs: {}

  # -- Resource requests and limits.
  # ref: https://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 1
      memory: 1Gi

  persistence:
    enabled: false
    ## A manually managed Persistent Volume and Claim
    ## If defined, PVC must be created manually before volume will be bound
    # existingClaim:
    # storageClass: "-"
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    annotations: {}

  # -- Node labels for pod assignment.
  # ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}
    # node-role.kubernetes.io/control-plane: ""

  # -- Tolerations for pod assignment.
  # ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []
    # - key: node-role.kubernetes.io/control-plane
    #   effect: NoSchedule

  # -- Affinity for pod assignment.
  # ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

vmselect:
  replicaCount: 1
  autoscaling:
    enabled: false

  extraArgs: {}

  # -- Resource requests and limits.
  # ref: https://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

  persistence:
    enabled: false
    ## A manually managed Persistent Volume and Claim
    ## If defined, PVC must be created manually before volume will be bound
    # existingClaim:
    # storageClass: "-"
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    annotations: {}

  # -- Node labels for pod assignment.
  # ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}
    # node-role.kubernetes.io/control-plane: ""

  # -- Tolerations for pod assignment.
  # ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []
    # - key: node-role.kubernetes.io/control-plane
    #   effect: NoSchedule

  # -- Affinity for pod assignment.
  # ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

vminsert:
  replicaCount: 1
  autoscaling:
    enabled: false

  extraArgs: {}

  # -- Resource requests and limits.
  # ref: https://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

  # -- Node labels for pod assignment.
  # ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}
    # node-role.kubernetes.io/control-plane: ""

  # -- Tolerations for pod assignment.
  # ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []
    # - key: node-role.kubernetes.io/control-plane
    #   effect: NoSchedule

  # -- Affinity for pod assignment.
  # ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

vmalert:
  replicaCount: 1
  autoscaling:
    enabled: false

  extraArgs: {}

  configMaps: []
  rulePath: []

  # -- Resource requests and limits.
  # ref: https://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

  # -- Node labels for pod assignment.
  # ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}
    # node-role.kubernetes.io/control-plane: ""

  # -- Tolerations for pod assignment.
  # ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []
    # - key: node-role.kubernetes.io/control-plane
    #   effect: NoSchedule

  # -- Affinity for pod assignment.
  # ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- Priority Class Name
# ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass
priorityClassName: ~

# -- Extra labels for pod.
# ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podlabels: {}

# -- Annotations for pod.
# ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
  # cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
