apiVersion: v1
kind: Secret
metadata:
  name: {{ include "headscale.fullname" . }}
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
type: Opaque
data:
  noise.key: {{ .Values.headscale.secrets.noise | b64enc | quote }}
  derp.key: {{ .Values.headscale.secrets.derp | b64enc | quote }}
