{{- if eq .Values.installationType "altinity" }}
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: {{ include "clickhouse.fullname" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
    {{- with .Values.podlabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  # troubleshoot: "no"
  namespaceDomainPattern: "%s.svc.{{ .Values.clusterDomain }}"
  defaults:
    templates:
      volumeClaimTemplate: data
      podTemplate: {{ include "clickhouse.fullname" . }}
      serviceTemplate: {{ include "clickhouse.fullname" . }}
  configuration:
    clusters:
      - name: {{ default (include "clickhouse.fullname" .) .Values.clickhouse.name }}
        layout:
          shardsCount: 1
          replicasCount: {{ .Values.replicaCount }}
    users:
      {{- if .Values.clickhouse.accessManagement }}
      default/networks/ip:
        - "::1"
        - "127.0.0.1"
      default/access_management: 1
      default/named_collection_control: 1
      default/show_named_collections: 1
      default/show_named_collections_secrets: 1
      {{- end }}
      {{- if .Values.backup.enabled }}
      backup/networks/ip:
        - "::/0"
        - "0.0.0.0/0"
      backup/password_sha256_hex: {{ include "clickhouse.backupPassword" . | sha256sum }}
      backup/profile: default
      backup/quota: default
      {{- end }}
      {{- range .Values.clickhouse.users }}
      {{ .name }}/profile: {{ .profile | default "default" }}
      {{ .name }}/quota: {{ .quota | default "default" }}
      {{- if .password_plain }}
      {{ .name }}/password: {{ .password_plain }}
      {{- else if .password }}
      {{ .name }}/password_sha256_hex: {{ .password }}
      {{- end }}
      {{ .name }}/networks/ip:
        - "::/0"
        - "0.0.0.0/0"
      {{- end }}
    profiles:
      readonly/readonly: 2
      reader/readonly: 2
    settings:
      {{- if .Values.metrics.enabled }}
      prometheus/endpoint: /metrics
      prometheus/port: 9363
      prometheus/metrics: true
      prometheus/events: true
      prometheus/asynchronous_metrics: true
      prometheus/status_info: true
      {{- end }}
      logger/level: {{ default "information" .Values.clickhouse.logLevel }}
    files:
      optimization.xml: |-
        <clickhouse>
            {{- include "clickhouse.optimization" . | nindent 12 }}
        </clickhouse>
      storage.xml: |-
        <clickhouse>
            {{- include "clickhouse.storage" . | nindent 12 }}
        </clickhouse>
    {{- if .Values.clickhouse.customConfig }}
      {{- range $key, $value := .Values.clickhouse.customConfig }}
      {{ $key }}: |-
        {{- $value | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if ne (len (default (list) .Values.clickhouse.zookeeper.nodes)) 0 }}
    zookeeper:
      {{- with .Values.clickhouse.zookeeper.nodes }}
      nodes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.clickhouse.zookeeper.root }}
      root: {{ .Values.clickhouse.zookeeper.root }}
      {{- end }}
      {{- if .Values.clickhouse.zookeeper.identity }}
      identity: {{ .Values.clickhouse.zookeeper.identity }}
      {{- end }}
    {{- end }}
  templates:
    volumeClaimTemplates:
      - name: data
        # reclaimPolicy: Retain
        metadata:
        {{- with .Values.persistence.annotations }}
          annotations:
          {{- range $key, $value := . }}
            {{ $key }}: {{ $value }}
          {{- end }}
        {{- end }}
        spec:
          accessModes:
          {{- range .Values.persistence.accessModes }}
            - {{ . | quote }}
          {{- end }}
          resources:
            requests:
              storage: {{ .Values.persistence.size | quote }}
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
          storageClassName: ""
        {{- else }}
          storageClassName: "{{ .Values.persistence.storageClass }}"
        {{- end }}
        {{- end }}
    podTemplates:
      - name: {{ include "clickhouse.fullname" . }}
        metadata:
          annotations:
          {{- with .Values.podAnnotations }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.metrics.enabled }}
            prometheus.io/scrape: "true"
            prometheus.io/port: "9363"
          {{- end}}
            checksum/envs: {{ toJson .Values.clickhouse.envs | sha256sum }}
        spec:
          enableServiceLinks: false
          {{- if .Values.priorityClassName }}
          priorityClassName: {{ .Values.priorityClassName }}
          {{- end }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 16 }}
          {{- end }}
          serviceAccountName: {{ include "clickhouse.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: "clickhouse"
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              {{- if .Values.clickhouse.envs }}
              envFrom:
                - secretRef:
                    name: {{ include "clickhouse.fullname" . }}-envs
              {{- end }}
              {{- if .Values.metrics.enabled }}
              ports:
                - name: metrics
                  containerPort: 9363
                  protocol: TCP
              {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
    serviceTemplates:
      - name: {{ include "clickhouse.fullname" . }}
        generateName: {{ include "clickhouse.fullname" . }}{{ ternary "" (printf "-%s" .Values.clickhouse.name) (eq .Values.clickhouse.name "") }}
        metadata:
          labels:
            {{- include "clickhouse.labels" . | nindent 12 }}
        spec:
          ports:
            - name: http
              port: 8123
            - name: client
              port: 9000
          type: ClusterIP
{{- end -}}
