---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: {{ include "victoria-metrics-storage.fullname" . }}
  labels:
    {{- include "victoria-metrics-storage.labels" . | nindent 4 }}
spec:
  useStrictSecurity: true
  retentionPeriod: "1"
  replicationFactor: 1

  vmstorage:
    disableAutomountServiceAccountToken: true
    priorityClassName: {{ .Values.priorityClassName | quote }}
    {{- if not .Values.vmStorage.autoscaling.enabled }}
    replicaCount: {{ .Values.vmStorage.replicaCount }}
    {{- end }}
    {{- with .Values.vmStorage.image }}
    image:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.vmStorage.extraArgs }}
    extraArgs:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.vmStorage.resources }}
    resources:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.vmStorage.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.vmStorage.tolerations }}
    tolerations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.vmStorage.affinity }}
    affinity:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if or .Values.podAnnotations .Values.podLabels }}
    podMetadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podLabels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    storageDataPath: "/vm-data"
    {{- if .Values.vmStorage.persistence.enabled }}
    storage:
      volumeClaimTemplate:
        metadata:
          name: data
          {{- with .Values.vmStorage.persistence.annotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          accessModes:
          {{- range .Values.vmStorage.persistence.accessModes }}
            - {{ . | quote }}
          {{- end }}
          resources:
            requests:
              storage: {{ .Values.vmStorage.persistence.size | quote }}
        {{- if .Values.vmStorage.persistence.storageClass }}
        {{- if (eq "-" .Values.vmStorage.persistence.storageClass) }}
          storageClassName: ""
        {{- else }}
          storageClassName: "{{ .Values.vmStorage.persistence.storageClass }}"
        {{- end }}
        {{- end }}
    {{- end }}

  vmselect:
    disableAutomountServiceAccountToken: true
    priorityClassName: {{ .Values.priorityClassName | quote }}
    {{- if not .Values.vmSelect.autoscaling.enabled }}
    replicaCount: {{ .Values.vmSelect.replicaCount }}
    {{- end }}
    {{- with .Values.vmSelect.image }}
    image:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.vmSelect.extraArgs }}
    extraArgs:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.vmSelect.resources }}
    resources:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.vmSelect.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.vmSelect.tolerations }}
    tolerations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.vmSelect.affinity }}
    affinity:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if or .Values.podAnnotations .Values.podLabels }}
    podMetadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podLabels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    cacheMountPath: "/select-cache"
    {{- if .Values.vmSelect.persistence.enabled }}
    storage:
      volumeClaimTemplate:
        metadata:
          name: data
          {{- with .Values.vmSelect.persistence.annotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          accessModes:
          {{- range .Values.vmSelect.persistence.accessModes }}
            - {{ . | quote }}
          {{- end }}
          resources:
            requests:
              storage: {{ .Values.vmSelect.persistence.size | quote }}
        {{- if .Values.vmSelect.persistence.storageClass }}
        {{- if (eq "-" .Values.vmSelect.persistence.storageClass) }}
          storageClassName: ""
        {{- else }}
          storageClassName: "{{ .Values.vmSelect.persistence.storageClass }}"
        {{- end }}
        {{- end }}
    {{- end }}

  vminsert:
    disableAutomountServiceAccountToken: true
    priorityClassName: {{ .Values.priorityClassName | quote }}
    {{- if not .Values.vmInsert.autoscaling.enabled }}
    replicaCount: {{ .Values.vmInsert.replicaCount }}
    {{- end }}
    {{- with .Values.vmInsert.image }}
    image:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.vmInsert.extraArgs }}
    extraArgs:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.vmInsert.resources }}
    resources:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.vmInsert.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.vmInsert.tolerations }}
    tolerations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.vmInsert.affinity }}
    affinity:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if or .Values.podAnnotations .Values.podLabels }}
    podMetadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podLabels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
