# Default values for pgbouncer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/sergelogvinov/pgbouncer
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

databases: {}
  # name:
  #   host: host
  #   port: 5432
  #   user: user
  #   dbname: dbname
  #   poolmode: session
  #   poolsize: 100

users: {}
  # name:
  #   poolmode: transaction
  #   connections: 100

# "username" "password"
# "md5" + "md5(password + username)" // echo -n '1234admin' | md5 -> md545f2603610af569b6155c45067268c6b
userlist:
  pgbouncer: pgbouncer

pgHbaConfiguration: |-
  # host  database    user                  address        auth-method
  host    all         all                   10.0.0.0/8     md5
  hostssl all         all                   0.0.0.0/0      md5

customSettings: {}

# -- Server TLS configuration.
# ref: https://www.pgbouncer.org/config.html#server_tls_sslmode
serverSslMode: allow
# -- Server TLS secret name (cert-manager).
serverSslSecret: ""

# -- Server TLS secrets.
# ref: https://www.pgbouncer.org/config.html#server_tls_ca_file
# ca, cert, key: If you want to use your own certificates, you can provide them here.
serverSsl: {}
  # ca: ""
  # cert: ""
  # key: ""

# -- Client TLS configuration.
# ref: https://www.pgbouncer.org/config.html#client_tls_sslmode
clientSslMode: allow
clientSslSecret: ""
  # pgbouncer-tls

# -- Extra labels for pod.
# ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

# -- Annotations for pod.
# ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}

# -- Pod Security Context.
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 999
  runAsGroup: 999
  fsGroup: 999
  fsGroupChangePolicy: "OnRootMismatch"

# -- Container Security Context.
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
securityContext:
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  # readOnlyRootFilesystem: true

# -- Service parameters
# ref: https://kubernetes.io/docs/user-guide/services/
service:
  type: ClusterIP
  port: 5432
  # nodePort: 5432

  annotations: {}
  # service.kubernetes.io/topology-mode: Auto

  ipFamilies: [IPv4]

# -- Resource requests and limits.
# ref: https://kubernetes.io/docs/user-guide/compute-resources/
resources:
  limits:
    # cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

# -- Horizontal pod autoscaler.
# ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- Use a daemonset instead of a deployment
useDaemonSet: false

terminationGracePeriodSeconds: 240

# -- pod deployment update stategy type.
# ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#updating-a-deployment
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1

# -- Priority Class Name
# ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass
priorityClassName: ~

# -- Node labels for pod assignment.
# ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

# -- Tolerations for pod assignment.
# ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

# -- Pod Anti Affinity
# soft/hard
podAntiAffinityPreset: soft

# -- Affinity for pod assignment.
# ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

metrics:
  enabled: false

  image:
    repository: jbub/pgbouncer_exporter
    tag: v0.18.0
    pullPolicy: IfNotPresent

  resources:
    limits:
      cpu: 100m
      memory: 32Mi
    requests:
      cpu: 10m
      memory: 16Mi
