# Default values for github-actions-runner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ghcr.io/sergelogvinov/github-actions-runner
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 9
  targetUtilizationPercentage: 90
  scaleDown:
    stabilizationWindowSeconds: 600
  scaleUp:
    stabilizationWindowSeconds: 30

runnerGroup: "default"
runnerScaleSetName: ""
# renovate: datasource=docker depName=ghcr.io/actions/gha-runner-scale-set-controller
runnerVersion: "0.10.1"

githubConfigUrl: "https://github.com/..."
githubConfigSecret:
  {}
  # github_token: "ghp_123"
  # github_app_id: ""
  # github_app_installation_id: ""
  # github_app_private_key: |

controllerServiceAccount:
  name: arc
  namespace: "" # cicd-controller

dind:
  enabled: true

  # -- Docker in Docker image.
  # ref: https://hub.docker.com/_/docker/tags?page=1&name=dind
  image:
    repository: docker
    pullPolicy: IfNotPresent
    tag: 26.1-dind

  # -- Resource requests and limits.
  # ref: https://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 256Mi

  # -- Additional container volume mounts.
  extraVolumeMounts: []
  # -- Additional volumes.
  extraVolumes: []

  # -- Persistence parameters for source code
  # ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
  persistence:
    enabled: false
    ## A manually managed Persistent Volume and Claim
    ## If defined, PVC must be created manually before volume will be bound
    # existingClaim:
    # storageClass: "-"
    accessModes:
      - ReadWriteOnce
    size: 100Gi
    annotations: {}

proxy:
  enabled: false

  image:
    repository: ubuntu/squid
    pullPolicy: IfNotPresent
    tag: "4.13-21.10_beta"

  command: ["/bin/sh", "/etc/proxy/proxy.sh"]

  # -- Resource requests and limits.
  # ref: https://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

  # -- Persistence parameters for source code
  # ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
  persistence:
    enabled: false
    ## A manually managed Persistent Volume and Claim
    ## If defined, PVC must be created manually before volume will be bound
    # existingClaim:
    # storageClass: "-"
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    annotations: {}

  # -- Node labels for mirrors deploy assignment.
  # ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}

  # -- Tolerations for mirrors deploy assignment.
  # ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

  # -- Anti-affinity for pod assignment.
  # options: soft, hard, null
  podAntiAffinityPreset: soft

  # -- Affinity for mirrors deploy assignment.
  # ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

mirrors:
  enabled: true

  image:
    repository: ghcr.io/project-zot/zot
    pullPolicy: IfNotPresent
    tag: "v2.1.1"

  # -- Container registry list.
  # ref: https://docs.docker.com/registry/recipes/mirror/
  registry:
    - host: docker.io
      source: https://registry-1.docker.io
      # auth:
      #   username: ""
      #   password: ""
    - host: gcr.io
      source: https://gcr.io
    - host: ghcr.io
      source: https://ghcr.io
      # auth:
      #   username: ""
      #   password: ""
    - host: registry.gitlab.com
      source: https://registry.gitlab.com
    - host: quay.io
      source: https://quay.io
    - host: mcr.microsoft.com
      source: https://mcr.microsoft.com
    - host: registry.k8s.io
      source: https://registry.k8s.io

  # -- Resource requests and limits.
  # ref: https://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi

  # -- Persistence parameters for source code
  # ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
  persistence:
    enabled: false
    ## A manually managed Persistent Volume and Claim
    ## If defined, PVC must be created manually before volume will be bound
    # existingClaim:
    # storageClass: "-"
    accessModes:
      - ReadWriteOnce
    size: 100Gi
    annotations: {}

  # -- Registry Service Account.
  # ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
  serviceAccount:
    # Specifies whether a service account should be created
    create: false
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  # -- Node labels for mirrors deploy assignment.
  # ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}

  # -- Tolerations for mirrors deploy assignment.
  # ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

  # -- Affinity for mirrors deploy assignment.
  # ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

registry:
  enabled: false

  image:
    repository: ghcr.io/project-zot/zot
    pullPolicy: IfNotPresent
    tag: "v2.1.2-rc4"

  storage:
    ~
    # rootDirectory: /var/lib/registry
    # commit: true
    # gc: true
    # gcDelay: "72h"
    # gcInterval: "4h"

  # -- Registry ingress parameters
  # ref: http://kubernetes.io/docs/user-guide/ingress/
  ingress:
    enabled: false
    className: ""

    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 0

    hosts:
      []
      # - host: chart-example.local

    tls:
      # - secretName: chart-example-tls
      #   hosts:
      #     - chart-example.local

    auth:
      {}
      # username: ""
      # password: ""
      # cert: ""
      # key: ""

  # -- Resource requests and limits.
  # ref: https://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi

  extraVolumeMounts: []
  extraVolumes: []

  # -- Persistence parameters for source code
  # ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
  persistence:
    enabled: false
    ## A manually managed Persistent Volume and Claim
    ## If defined, PVC must be created manually before volume will be bound
    # existingClaim:
    # storageClass: "-"
    accessModes:
      - ReadWriteOnce
    size: 100Gi
    annotations: {}

  # -- Registry Service Account.
  # ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
  serviceAccount:
    # Specifies whether a service account should be created
    create: false
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  # -- Node labels for local registry deploy assignment.
  # ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}

  # -- Tolerations for local registry deploy assignment.
  # ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

  # -- Affinity for local registry deploy assignment.
  # ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

metrics:
  enabled: false

  image:
    repository: ghcr.io/sergelogvinov/github-actions-exporter
    pullPolicy: IfNotPresent
    tag: "v1.9.0-beta"

  # -- Resource requests and limits.
  # ref: https://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 192Mi

  # -- Node labels for local registry deploy assignment.
  # ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}

  # -- Tolerations for local registry deploy assignment.
  # ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

  # -- Affinity for local registry deploy assignment.
  # ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

# -- Github Actions Runner Listener parameters
listener:
  # -- Node labels for pod assignment.
  # ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}

  # -- Tolerations for pod assignment.
  # ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

  # -- Affinity for pod assignment.
  # ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

# -- Pods Service Account.
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Annotations for pod.
# ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}

# -- Pod Security Context.
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
podSecurityContext:
  {}
  # fsGroup: 0
  # fsGroupChangePolicy: "OnRootMismatch"

# -- Container Security Context.
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
securityContext:
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
  runAsUser: 1001
  runAsGroup: 0

# -- Service parameters
# ref: https://kubernetes.io/docs/user-guide/services/
service:
  ipFamilies: [IPv4]

# -- Resource requests and limits.
# ref: https://kubernetes.io/docs/user-guide/compute-resources/
resources:
  # limits:
  #   cpu: 1
  #   memory: 768Mi
  requests:
    cpu: 200m
    memory: 512Mi

# -- Persistence parameters for source code
# ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
persistence:
  enabled: false
  ## A manually managed Persistent Volume and Claim
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:
  # storageClass: "-"
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  annotations: {}

# -- Additional container volume mounts.
extraVolumeMounts: []
#   - name: tlscerts
#     mountPath: /home/runner/.docker

# -- Additional volumes.
extraVolumes: []
#   - name: tlscerts
#     secret:
#       secretName: cnt-builder
#       defaultMode: 256
#       items:
#         - key: ca.crt
#           path: ca.pem
#         - key: tls.crt
#           path: cert.pem
#         - key: tls.key
#           path: key.pem

# -- Node labels for pod assignment.
# ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

# -- Tolerations for pod assignment.
# ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

# -- Anti-affinity for pod assignment.
# options: soft, hard, null
podAntiAffinityPreset: soft

# -- Affinity for pod assignment.
# ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}
