apiVersion: v1
kind: Secret
metadata:
  name: {{ include "link-common.fullname" . }}
  labels:
    {{- include "link-common.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.wireguard.enabled }}
  wg0.conf: {{ include "link-common-wireguard.conf" . | b64enc }}
{{- end}}
{{- if and .Values.tailscale.enabled .Values.tailscale.envsSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "link-common.fullname" . }}-envs
  labels:
    {{- include "link-common.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $name, $value := .Values.tailscale.envsSecrets }}
  {{ $name }}: {{ tpl $value $ | b64enc | quote }}
{{- end}}
{{- end}}
