apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-single.fullname" . }}
  labels:
    {{- include "postgresql-single.labels" . | nindent 4 }}
type: Opaque
data:
  postgresqlPassword: {{ include "postgresql-single.postgresqlPassword" . | b64enc | quote }}
  {{- if .Values.backup.enabled }}
  walg.yaml: {{ include "postgresql-single.walg" . | b64enc | quote }}
  {{- end }}
