{{- if and .Values.podDisruptionBudget.create (gt (.Values.replicaCount | int) 1) }}
{{- if eq .Values.installationType "standalone" }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "postgresql-single.fullname" . }}
  labels:
    {{- include "postgresql-single.labels" . | nindent 4 }}
    {{- with .Values.podlabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "postgresql-single.selectorLabels" . | nindent 6 }}
  maxUnavailable: {{ default 1 .Values.podDisruptionBudget.maxUnavailable }}
{{- end }}
{{- end }}
