name: HelmChart Check

on:
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  helm-lint:
    name: Helm chart check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Install chart-testing tools
        id: lint
        uses: helm/chart-testing-action@v2.6.1

      - name: Run helm chart linter
        run: ct lint --config .github/ct.yml --lint-conf .github/lintconf.yaml
