name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 2" # every Tuesday at 9:00 UTC

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-24.04
    permissions:
      checks: read
      contents: write
      issues: write
      pull-requests: write
      security-events: read
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6

      # Everything runs in container, use docker-cmd-file to add packages
      - name: Renovate
        uses: renovatebot/github-action@5402b206248e5a8c8427a15102702eb9c1793efc # v46.2.4
        with:
          renovate-image: ghcr.io/sergelogvinov/renovate
          renovate-version: 40
          configurationFile: .github/renovate-global.json5
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: "debug"
