name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 2" # every Tuesday at 9:00 UTC

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-24.04
    permissions:
      checks: read
      contents: write
      issues: write
      pull-requests: write
      security-events: read
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      # Everything runs in container, use docker-cmd-file to add packages
      - name: Renovate
        uses: renovatebot/github-action@dd5302ec17783b2fc721b19ae7209b57b1587765 # v46.1.17
        with:
          renovate-image: ghcr.io/sergelogvinov/renovate
          renovate-version: 40
          configurationFile: .github/renovate-global.json5
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: "debug"
