- name: mongodb.rules
  rules:
  - alert: MongoDBReplicationLagIsTooLarge
    expr: mongodb_mongod_replset_member_replication_lag{state="SECONDARY"} > 86400
    for: 1m
    labels:
      severity: critical
    annotations:
      description: MongoDB replication lag of {{$labels.app_kubernetes_io_instance}} in cluster {{$labels.cluster}} is more than 24 hours
      summary: MongoDB replication lag is more than 24 hours
  - alert: MongoDBInstanceIsTooLongInStartup2State
    expr: lifetime((mongodb_mongod_replset_my_state == 5)[24h]) > 86400
    for: 1m
    labels:
      severity: critical
    annotations:
      description: MongoDB pod {{$labels.kubernetes_pod_name}} of {{$labels.app_kubernetes_io_instance}} in cluster {{$labels.cluster}} is in the STARTUP2 state more than 24 hours
      summary: MongoDB pod is in the STARTUP2 state more than 24 hours
  - alert: MongoDBInstanceNorPrimaryNorSecondary
    expr: mongodb_mongod_replset_my_state != 1 and mongodb_mongod_replset_my_state != 2
    for: 15m
    labels:
      severity: warning
    annotations:
      description: MongoDB pod {{$labels.kubernetes_pod_name}} of {{$labels.app_kubernetes_io_instance}} in cluster {{$labels.cluster}} is not in the right state
      summary: MongoDB pod is nor Primary nor Secondary
